# Generated by Django 5.2.18 on 2026-10-07 01:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('codigo', models.CharField(blank=True, help_text='Código interno ou de barras (opcional).', max_length=50, null=True, unique=True, verbose_name='código')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço de venda')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='quantidade em estoque')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['nome'],
            },
        ),
    ]
