# Generated by Django 5.2.18 on 2026-10-07 01:54

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('papel', models.CharField(choices=[('administrador', 'Administrador'), ('vendedor', 'Vendedor')], default='vendedor', help_text='Define o que o usuário pode fazer no sistema. Administradores também acessam o painel /admin.', max_length=20, verbose_name='papel')),
                ('telefone', models.CharField(blank=True, max_length=15, validators=[core.validators.validar_telefone], verbose_name='telefone')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
    ]
