# Generated by Django 5.2.18 on 2026-10-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_criar_perfis_existentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='papel',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('vendedor', 'Vendedor')], default='vendedor', help_text='Vendedor: vê apenas as próprias vendas. Gerente: vê as vendas de todos, os dashboards gerenciais e acessa o painel /admin.', max_length=20, verbose_name='papel'),
        ),
    ]
