# Generated by Django 5.2.18 on 2026-10-07 01:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data_venda', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data da venda')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('debito', 'Cartão de débito'), ('credito', 'Cartão de crédito'), ('promissoria', 'Promissória')], max_length=20, verbose_name='forma de pagamento')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12, verbose_name='valor total')),
                ('status', models.CharField(choices=[('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='concluida', max_length=20, verbose_name='situação')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cliente', models.ForeignKey(blank=True, help_text='Obrigatório para vendas em promissória.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='clientes.cliente')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade')),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Preço no momento da venda. Se ficar vazio, usa o preço atual do produto.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço unitário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='produtos.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'item da venda',
                'verbose_name_plural': 'itens da venda',
            },
        ),
    ]
