# Generated by Django 5.2.18 on 2026-10-07 01:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('cpf', models.CharField(blank=True, help_text='Com ou sem pontuação. É salvo somente com números.', max_length=14, null=True, unique=True, validators=[core.validators.validar_cpf], verbose_name='CPF')),
                ('telefone', models.CharField(max_length=15, validators=[core.validators.validar_telefone], verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
            },
        ),
    ]
