# Generated by Django 5.2.18 on 2026-10-07 01:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promissoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('numero', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='número')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('data_emissao', models.DateField(default=django.utils.timezone.localdate, verbose_name='data de emissão')),
                ('data_vencimento', models.DateField(verbose_name='data de vencimento')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='status')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10, verbose_name='valor pago')),
                ('data_pagamento', models.DateField(blank=True, editable=False, null=True, verbose_name='data do pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promissorias', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promissorias_criadas', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promissorias', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'promissória',
                'verbose_name_plural': 'promissórias',
                'ordering': ['data_vencimento', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor pago')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.localdate, verbose_name='data do pagamento')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('debito', 'Cartão de débito'), ('credito', 'Cartão de crédito')], max_length=20, verbose_name='forma de pagamento')),
                ('observacoes', models.CharField(blank=True, max_length=255, verbose_name='observações')),
                ('cancelado', models.BooleanField(default=False, verbose_name='cancelado')),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255, verbose_name='motivo do cancelamento')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_recebidos', to=settings.AUTH_USER_MODEL)),
                ('promissoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='promissorias.promissoria')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-data_pagamento', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPromissoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('acao', models.CharField(max_length=50, verbose_name='ação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('promissoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='promissorias.promissoria')),
            ],
            options={
                'verbose_name': 'histórico da promissória',
                'verbose_name_plural': 'histórico das promissórias',
                'ordering': ['-data', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='promissoria',
            index=models.Index(fields=['status', 'data_vencimento'], name='promissoria_status_b75541_idx'),
        ),
    ]
